security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
            App\Entity\User: bcrypt
    providers:
            database_users:
                        entity: { class: App\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # les urls auxquels s'appliquent ce firewall, dans ce cas, ce sont toutes les urls
            pattern: ^/

            # La connexion n'est pas requise sur toutes les pages
            # par exemple la page d'accueil
            anonymous: true

            form_login:
                # Le nom de la route de la page de connexion
                check_path: adminLogin
                # Le nom de la route où se trouve le formulaire de connexion
                # Si un utilisateur tente d'acceder à une page protégée sans en avoir les droits
                # il sera redirigé sur cette page
                login_path: adminLogin
                # Securisation des formulaires
                csrf_token_generator: security.csrf.token_manager
                # La page par defaut apres une connexion reussie
                default_target_path: adminHome

            logout:
                # La route où se trouve le process de deconnexion
                path: adminLogout
                # La route sur laquelle doit etre rediriger l'utilisateur apres une deconnexion
                target: home

    access_control:
            # Les regles de securité
            # Là dans ce cas seul les utilisateurs ayant le rôle ROLE_ADMIN
            # peuvent acceder à toutes les pages commençant par /admin
            - { path: '^/admin', roles: ROLE_ADMIN }

          # - { path: ^/profile, roles: ROLE_USER }

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html